server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usersdb
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  name: user-service
  description: User management service
